version: '3.4'

services:
  gsl.productapi:
    image: ${DOCKER_REGISTRY-}gslproductapi
    build:
      context: .
      dockerfile: GSL.ProductAPI/Dockerfile
    ports:
      - "30565:80" 
    depends_on:
      - database

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: webapidb
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "saLocal0"
    volumes:
      - sqlsystem:/var/opt/mssql/
volumes:
  sqlsystem: