version: '3.4'

services:
  gslweb:
    image: docker.io/caiotfgv/gslweb:latest  
    container_name: gslweb
    ports:
      - "2222:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - gslnetwork
    depends_on:
      - mssql
      - keycloak
    restart: on-failure

  gslproductapi:
    image: docker.io/caiotfgv/gslproductapi:latest  
    container_name: gslproductapi
    networks:
      - gslnetwork
    ports:
      - "5555:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_ENDPOINT=mssql
      - DB_MIGRATE=true
      - DB_INITIALIZE=true        
    depends_on:
      - mssql
      - keycloak
    restart: on-failure

  gslratingapi:
    image: docker.io/caiotfgv/gslratingapi:latest  
    container_name: gslratingapi
    networks:
      - gslnetwork
    ports:
      - "4444:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_ENDPOINT=mssql
      - DB_MIGRATE=true
      - DB_INITIALIZE=true  
    depends_on:
      - mssql
      - keycloak
    restart: on-failure

  gslapigateway:
    image: docker.io/caiotfgv/gslapigateway:latest 
    container_name: gslapigateway
    networks:
      - gslnetwork
    ports:
      - "7777:80" 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - gslproductapi
      - gslratingapi
    restart: on-failure

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    networks:
      - gslnetwork
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "saLocal0"
    restart: always

  mysql:
    image: docker.io/mysql:latest
    container_name: mysql
    networks:
        - gslnetwork
    environment:
        - MYSQL_DATABASE=keycloak
        - MYSQL_USER=keycloak
        - MYSQL_PASSWORD=password
        - MYSQL_ROOT_PASSWORD=root_password
        - MYSQL_ROOT_HOST=%
    ports:
        - 3306:3306
    restart: always

  keycloak:
    image: docker.io/jboss/keycloak:latest
    container_name: keycloak
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    environment:
        - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
        - KEYCLOAK_FRONTEND_URL=http://localhost:8080/auth
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
        - DB_VENDOR=mysql
        - DB_ADDR=mysql
        - DB_PORT=3306
    ports:
        - 8080:8080
    depends_on:
        - mysql
    networks:
        - gslnetwork

networks:
    gslnetwork:
        driver: bridge 
       